server {
    listen 80;
    server_name portal.hundredfold.digital;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name portal.hundredfold.digital;

    ssl_certificate     /etc/letsencrypt/live/portal.hundredfold.digital/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portal.hundredfold.digital/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    location /static/ {
        alias /var/www/employee_portal/static/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /uploads/ {
        alias /var/www/employee_portal/secure_vault/;
        internal;
    }

    location / {
        proxy_pass         http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 300s;
    }
}
